### ISSUE TITLE
Реализовать GetLine

### ISSUE THREAD

**Issue by khokm** [khokm/stratum-player#13]
`Text := GetLine (~HStream,255,Chr(13))`
Нужна для доставания id проекта из файла.
 
Сам проект:
http://stratum.ac.ru/enteronline/task.php?s=3&c=7&t=1/1

**Comment by khokm** [comment]
Почему используется `GetLine`? Разве не лучше было бы использовать `ReadLn`? В данном случае мы хотим читать текст до конца строки; как раз это `ReadLn` и делает, при том ей достаточно одного аргумента.

**Comment by Sogi-IIT** [comment]
Ок поменял на `ReadLn`. Упражнение работает.
Но, возможно, в будущем все равно встретится и `GetLine`.
