### ISSUE TITLE
Реализация шифрования и дешифрования файла ToSend.xml

### ISSUE THREAD

**Issue by Sogi-IIT** [khokm/stratum-player#18]
Можно ли добавить шифрование данного файла на этапе его записывания. 
Как это лучше сделать? в твоем коде (в webe) или в самом стратуме предусмотреть.

Так же нужен и дешифратор файла на сервере.

В данный момент можно вручную менять оценки)

**Comment by Salaron** [comment]
Можно не только вручную менять оценки, перехватывая файл и меняя значения в нём, но также можно отправлять свои запросы на сервер с фейковыми данными, даже не открывая упражнение.
Лучше будет шифровать файл каким-нибудь временным ключом, полученным с сервера при открытии задания.

**Comment by khokm** [comment]
@Sogi-IIT даже реализовав шифрование, предложенное @Salaron, пользователь все равно сможет получить этот самый ключ - посмотрев запросы во вкладке Network. Кроме того, ничего не мешает ему скачать оттуда же архив с упражнением и отредактировать код создания файла так, чтобы туда писалась только оценка 5. Запаролив архивы мы все равно вынуждены будем передавать этот пароль для распаковки, и он будет виден в Network.
Единственный правильный способ - запретить клиенту оценивать самого себя. Должны только отсылаться данные задания на сервер, и тот должен уже решать, правильно ли решено задание, или нет.

**Comment by Sogi-IIT** [comment]
@khokm
Запретить клиенту оценивать самого себя мы пока не можем.
Предлагаю сделать простейшее (чтобы по времени не сильно затратное) шифрование на твой выбор.

**Comment by khokm** [comment]
@Sogi-IIT в таком случае, лучше сделать это в стратуме.
Остается только проблема того, что архив можно скачать и изменить имиджи. Все, что я могу предложить - сделать программу, которая перед запаковкой "испортит" файлы имиджей (ну и, соответственно, доработать код разбора формата файлов, чтобы он умел читать такие "испорченные" файлы).

**Comment by khokm** [comment]
Согласно докам, `CreateDib2D` создает инструмент "Битовая карта".
Однако, в реальности, если используется формат GIF, он создает двойную битовую карту, так что возвращаемый ею дескриптор возможно использовать для вызова `CreateDoubleBitmap2D`. Мда.
![image](https://user-images.githubusercontent.com/25861783/128591494-32b36e53-38db-4201-b3b1-550e1f8a38bf.png)
