### ISSUE TITLE
Ошибка парсинга имиджа ControlZakladka

### ISSUE THREAD

**Issue by khokm** [khokm/stratum-player#23]
http://stratum.ac.ru/enteronline/task.php?s=3&c=7&t=1/9

**Comment by khokm** [comment]
@Sogi-IIT, нужно убрать вот эту вот тильду.
Компилятор Stratum 2000, коряво написан и пропускает подобные синтаксические ошибки; компилятор stratum-player - нет.
![image](https://user-images.githubusercontent.com/25861783/128564189-d455a95b-83ce-4651-b619-55457a5bb010.png)

**Comment by Sogi-IIT** [comment]
это я уже исправил!
Ведет себя не совсем так как нужно., повторить не смогу. 
в данный момент задачу закрываем.

**Comment by khokm** [comment]
@Sogi-IIT "ведет себя не совсем как нужно" - что имелось ввиду?

**Comment by Sogi-IIT** [comment]
Можно закрывать.
