### ISSUE TITLE
Добавить чтение JPEG и GIF

### ISSUE THREAD

**Issue by khokm** [khokm/stratum-player#25]
Проект для примера:
http://stratum.ac.ru/enteronline/task.php?s=3&c=7&t=1/3

**Comment by Salaron** [comment]
Занимаюсь переписыванием декодера JPEG на TS.
Прошу оставить этот таск мне.

**Comment by khokm** [comment]
@Salaron вообще-то у меня были мысли вообще отказаться от каких бы-то ни было декодеров, в т.ч. от используемого сейчас декодера BMP.
Вместо этого предлагаю кодировать [ArrayBuffer изображения в base64 data URL](https://gist.github.com/candycode/f18ae1767b2b0aba568e).
А дальше полученную data url используем следующим образом:
```javascript
//блокировка выполнения имиджа
img = new Image();
img.onload = () => {
     //изображение загружено, разблокировка выполнения имиджа
};
img.src = data_url;
```
Пусть эту работу выполняет браузер, тем более что он будет подгружать изображение в фоне, не блокируя main thread.

**Comment by Salaron** [comment]
@khokm Хм, а в IE9 это будет работать? 
И что насчёт GIF? Насколько я знаю, стратум тоже не особо с ним дружит и отображает только первый фрейм.

**Comment by khokm** [comment]
@Salaron на IE9 я никогда и не рассчитывал. В нем нет TypedArray, на которых основано все чтение форматов файлов.
На IE11, кстати, тоже - но если такая задача появится, там немного мест, которые придется покрыть полифилами.

**Comment by khokm** [comment]
Согласно докам, `CreateDib2D` создает инструмент "Битовая карта".
Однако, в реальности, если используется формат GIF, он создает двойную битовую карту, так что возвращаемый ею дескриптор возможно использовать для вызова `CreateDoubleBitmap2D`. Мда.
![image](https://user-images.githubusercontent.com/25861783/128591494-32b36e53-38db-4201-b3b1-550e1f8a38bf.png)
