### ISSUE TITLE
Точки мигают слишком быстро после переключения вкладок

### ISSUE THREAD

**Issue by khokm** [khokm/stratum-player#36]
http://stratum.ac.ru/enteronline/task.php?s=3&c=7&t=1/1
Нужно запустить проект, запустить мигание точки и переключиться на другую вкладку (или свернуть браузер).
По возвращении на вкладку точка будет мигать с гораздо большей частотой.
Это связано с тем, что в свернутых вкладках выполнение функции, что вызывает выполнение имиджей приостанавливается браузером.

Воспроизвести на Windows можно так: запустить мигание точки - пауза - подождать - продолжить - поводить курсором над окном.
![bug](https://user-images.githubusercontent.com/25861783/128920831-468472b4-04c8-41f2-b038-fdfb773ec288.gif)
также настроив проект на выполнение циклов по таймеру через 16ms.
@Sogi-IIT, рекомендую как-нибудь поправить имидж _Blink_2_.

**Comment by Sogi-IIT** [comment]
можно закрывать
