### ISSUE TITLE
Функция MObr(FLOAT Q1, FLOAT Q2, FLOAT Flag)

### ISSUE THREAD

**Issue by Sogi-IIT** [khokm/stratum-player#40]
http://stratum.ac.ru/enteronline/task.php?s=1&c=7-9&t=2/1/14

Имидж MoveAnimateObject2d / Graf

Функция вычисляет обратную матрицу к Q1 и помещает её в новую Q2

**Comment by khokm** [comment]
Недокументировано: возвращает 0, если матрица вырожденная

**Comment by Sogi-IIT** [comment]
Ну если она вырожденная значит обратной нет. Так что нормально что возвращает 0.

**Comment by khokm** [comment]
@Sogi-IIT, правильно, но такие вещи должны по идее должны документироваться.
Алсо, что делать с прямоугольными матрицами? Нужна их поддержка?

**Comment by khokm** [comment]
@Salaron возможно тебе это поручить? Нужно, чтобы работало так:
Если матрица вырожденная или не квадратная, то возвращать 0 и ничего не делать.

Немного алгоритмов.
https://gist.github.com/husa/5652439
https://github.com/josdejong/mathjs/blob/develop/src/function/matrix/inv.js

**Comment by Salaron** [comment]
@khokm да, могу попробовать.
