### ISSUE TITLE
Баг в проекте

### ISSUE THREAD

**Issue by khokm** [khokm/stratum-player#50]
http://stratum.ac.ru/enteronline/task.php?s=1&c=7-9&t=1/1/1
Если быстро щелкать по "Далее", то возможно запустить проект повторно.
Следует блокировать эту кнопку после нажатия и разблокировать после выхода из подпроекта.
![bug1](https://user-images.githubusercontent.com/25861783/129041093-c198d352-6a9d-46a8-bcd7-4e7435e16cbb.gif)

**Comment by khokm** [comment]
Тот же проект.
Таблица перекрывает шапку.
![image](https://user-images.githubusercontent.com/25861783/129046026-b02c4c39-8d89-4707-8055-0067c24adbb6.png)

**Comment by Sogi-IIT** [comment]
Исправил. Можно закрывать
