### ISSUE TITLE
Ошибка чтения GIF

### ISSUE THREAD

**Issue by Salaron** [khokm/stratum-player#51]
Задание: http://stratum.ac.ru/enteronline/task.php?s=1&c=7-9&t=1/2/22
Gif считывается как DBM.
![image](https://user-images.githubusercontent.com/27885055/129175970-510b0457-5528-4ddd-a935-d31f54cc83cd.png)

Полагаю, что это происходит [здесь](https://github.com/khokm/stratum-player/blob/master/src/stratum/fileFormats/vdr/readers.ts#L76).

**Comment by khokm** [comment]
Там же:
 - главное окно не закрывается при открытии подпроекта;
 - не реализован запуск calc.exe.
