### ISSUE TITLE
Окно имеет нулевые размеры

### ISSUE THREAD

**Issue by khokm** [khokm/stratum-player#57]
http://stratum.ac.ru/enteronline/task.php?s=1&c=7-9&t=2/1/14
По нажатии "Текст" создается окно размером 1x1.

**Comment by Sogi-IIT** [comment]
Вопрос! 
В стратуме работает и так) окно само устанавливается под размеры находящегося объекта в схеме имиджа.
Придется все такие проекты поправлять? и при создании окна вручную устанавливать размеры

**Comment by khokm** [comment]
Не придётся, исправлю.11:58, 13 августа 2021 г., "Sogi-IIT" ***@***.***>:
Вопрос!
В стратуме работает и так) окно само устанавливается под размеры находящегося объекта в схеме имиджа.
Придется все такие проекты поправлять? и при создании окна вручную устанавливать размеры

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by Sogi-IIT** [comment]
супер!
