### ISSUE TITLE
Сохранение матриц

### ISSUE THREAD

**Issue by Sogi-IIT** [khokm/stratum-player#60]
http://stratum.ac.ru/enteronline/task.php?s=1&c=7-9&t=2/1/1

Пишет что сохранение матриц не реализовано.
Функции 
Msaveas(Num,name,Flag) - сохранить
Mload(Num,name,Flag) - загрузить

**Comment by Salaron** [comment]
@khokm посмотри на реализацию: https://github.com/Salaron/stratum-player/commit/80cd3d497f0113ab82968a4d08b275be77729983
Мне она не особо нравится, поэтому пока PR не буду открывать.

**Comment by Salaron** [comment]
Также в этом проекте: "Команда CM_PREVPAGE не реализована."

**Comment by khokm** [comment]
@Sogi-IIT нужен проект который сохраняет матрицу в файл и затем читает ее оттуда.

**Comment by khokm** [comment]
@Salaron да, я переделал это в #62.
