### ISSUE TITLE
Элемент ввода Button и функция enableControl2d не реализованы

### ISSUE THREAD

**Issue by Sogi-IIT** [khokm/stratum-player#68]
http://stratum.ac.ru/enteronline/task.php?s=1&c=7-9&t=1/5/4

В проектах встречается старая кнопка. 
Участия в жизни проекта не принимает.
Можно как то её игнорировать?
Я задолбаюсь их искать и удалять из проектов)

**Comment by khokm** [comment]
@Sogi-IIT не стоит тратить время на исправление проектов, пока не будет точно ясно, что по-другому это не исправить.
Оптимальнее просто сообщать об ошибках и проверять другие проекты.

**Comment by Sogi-IIT** [comment]
да тут в физике приходится подправлять всякое. ладно хоть почти всё однотипное)
Давно её делали. Всем не до нее было. 
Можно закрывать
